### ISSUE TITLE
Set up design token sync

### ISSUE THREAD

**Issue by tobiasljungstrom** [SKF/design-systems#24]
See the setup in https://github.com/skfccoe/design-system for how to do it.

**Comment by tobiasljungstrom** [comment]
We can set up the syncing now, but when it comes to editing the tokens themselves we should talk to Mani first.

**Comment by stt-tomahl** [comment]
It's important that we establish a logical naming-pattern that is self-documented, where closely related variables hold together.

` --[area|context|property]-[definition]: [value];`

Example:
```
--color-blue: #00f;
--color-red: #f00;

--font-size-md: 1rem;
--font-size-lg: 1.5rem;

--spacing-md: 1rem;
--spacing-lg: 1.5rem;

/**
 * Button
 */
--button-color: var(--color-blue);
--button-font-size: var(--font-size-md);
--button-padding-lg: var(--spacing-lg);
```

We should avoid spread naming for related (button in this case) tokens like below:
```
--[button]-color: var(--color-blue);
--font-size-[button]: var(--font-size-md);
--padding-[button]-lg: var(--spacing-lg);
```

**Comment by stt-tomahl** [comment]
In my opinion we should place all global tokens at root level in the "src" folder e.g.

```
src/tokens/fonts/fonts.ts
src/tokens/colors/colors.ts
src/tokens/motion/motion.ts
src/tokens/spacings/spacings.ts
```

 to keep them as stand-alone consumable resources to be used in both the ui-library and other projects.

As for component specific tokens, they should be placed at component level and should **only** export tokens that are of value to others.

**Comment by tobiasljungstrom** [comment]
Should we export tokens from our lib? It is true that it might be convenient for the users, but at the same time they might want to update their tokens without updating their component dependency.

Maybe it fine to both export them from us, and have them available from DSM.
