### ISSUE TITLE
Create and use a separate board for code-related issues?

### ISSUE THREAD

**Issue by stt-tomahl** [SKF/design-systems#32]
Should we use a separate board for code/ui-lib related issues and one for the team?

**Comment by tobiasljungstrom** [comment]
Yeah. :)

So like:

Board 1: Bugs, improvements, new features, and other issues related to the product and its development

Board 2: Team processes, internal todos, meetings, reminders etc.

**Comment by stt-tomahl** [comment]
Exactly 

> Yeah. :)
> 
> So like:
> 
> Board 1: Bugs, improvements, new features, and other issues related to the product and its development
> 
> Board 2: Team processes, internal todos, meetings, reminders etc.

Excatly 👍

**Comment by tobiasljungstrom** [comment]
We should move all issues to the right place, then we can close this.
